### ISSUE TITLE
(MacOS distribution) What entitlements are required for electron-store?

### ISSUE THREAD

**Issue by hugozap** [sindresorhus/electron-store#101]
I'm trying to sign and notarize a mac application.
Because of the sandbox security model I need to specify what entitlements and paths are going to be needed.

I wonder what specific values would be needed for electron-store to avoid errors? 
Thanks.

**Comment by sindresorhus** [comment]
None. macOS just automatically redirects to paths to be inside the sandbox. This package should *just work*.
