### ISSUE TITLE
EXDEV: cross-device link not permitted, rename

### ISSUE THREAD

**Issue by mifi** [sindresorhus/electron-store#106]
A user of my electron app is getting this error on Windows:

![78456447-004d4700-76a4-11ea-83fc-3d13ab5d6cb7](https://user-images.githubusercontent.com/402547/78457354-24c51580-76dc-11ea-8dd4-a1ea6485af47.png)

See https://github.com/mifi/lossless-cut/issues/292

It is renaming from one drive to the same drive, so I'm not sure why it's giving this error, but it could be some virtual drive stuff going on on windows, especially when running as an `appx` from Windows Store.

I found that npm had the same issue before:
https://github.com/npm/npm/issues/13306#issuecomment-236876133

...also not really cross-device moving, but it crashes still.

It seems like node-fs-extra already has built-in support for handling this case:
- https://github.com/jprichardson/node-fs-extra/pull/170
- https://github.com/jprichardson/node-fs-extra/pull/549
- https://github.com/jprichardson/node-fs-extra/blob/40c3d68eb4fc4aa9a3c5624b4160610af296ec2e/lib/move/move.js#L49

I see that in `Conf`, which `electron-store` is using, you are using `write-file-atomic`, which is the one that is throwing `EXDEV`. Maybe better to switch to the more robust fs-extra, or at least catch EXDEV and then instead copy/delete the file? What do you think?

**Comment by mifi** [comment]
I fake reproduced this error by modifying my `lossless-cut/node_modules/write-file-atomic/index.js` and adding:

```
...
    if (options.chown) fs.chownSync(tmpfile, options.chown.uid, options.chown.gid)
    if (options.mode) fs.chmodSync(tmpfile, options.mode)


    const testErr = new Error("EXDEV: cross-device link not permitted, rename '...' -> '....'");
    testErr.errno = -18;
    testErr.syscall = 'rename';
    testErr.code = 'EXDEV';
    testErr.path = '/Users/mifi/test.txt';
    testErr.dest = '/Volumes/travelstick2tb/test.txt';
    throw testErr;


    fs.renameSync(tmpfile, filename)
    threw = false
...
```

**Comment by mifi** [comment]
I have created a PR, and tested that it works with my fake reproduced error.

**Comment by mifi** [comment]
We could have added workaround in `write-file-atomic` instead, but I feel that it will violate the purpose of that package, because the write can no longer be atomic when this error occurs.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/conf/releases/tag/v6.2.3

Just reinstall `electron-store` to get it.

**Comment by sindresorhus** [comment]
This sounds more like a Node.js bug to me. `EXDEV` should not be thrown when they're in the same directory, AFAIK.

**Comment by mifi** [comment]
I feel more like it’s an OS bug or limitation in Windows 10. Im pretty sure the low level api call rename is giving this error to nodejs. since rename is specified to be atomic, then it has to throw because doing anything else would break its atomicity guarantee. It kind of sucks because it’s a special case that any developer who uses rename (or write-file-atomic) needs to handle. And it is very obscure and hard to reproduce
