### ISSUE TITLE
operation not permitted rename

### ISSUE THREAD

**Issue by xu455255849** [sindresorhus/electron-store#107]
![image](https://user-images.githubusercontent.com/15166243/79223675-5f713f80-7e8c-11ea-9778-7f889600a9b8.png)

OS: Windows 7
Electron: 4.1.1
electron-store@^4.0.0

read the doc  careful， i see  Requires Electron 5 or later.  
is this reason to  create this problem？

**Comment by mifi** [comment]
duplicate of #103

**Comment by bei-yang** [comment]
大佬这个错误怎么做的，还在用这个库吗？我看上面的回答，升级包也没解决...
