### ISSUE TITLE
The migration feature is broken

### ISSUE THREAD

**Issue by AlyxMoon** [sindresorhus/electron-store#108]
Current version: 5.1.1

I'm making this because it was unexpected behavior. I wanted to use migrations, and applying them works fine the first time. However, internally, this app adds a key to track which migrations have been run, by default:
```
"__internal__": {
    "migrations": {
      "version": version_number
    }
  }
```

The underlying assumption based upon the documentation here and on the `conf` package this uses, is that the version_number will be the version of my application's package.json
However, using electron-store, it applies the version of electron-store instead, so at the moment it is always 5.1.1 regardless of my app's version, causing my future migrations not to run if they are below that.

Not sure if this should be fixed in this app to somehow point correctly to my app's package.json or in `conf` code's check of what package.json to use.

**Comment by AlyxMoon** [comment]
Easy enough workaround for now though, just setting the projectVersion as mentioned in the docs:

```js
import packageData from 'package.json'
...

const config = new Store({
  ...
  projectVersion: packageData.version
})
```

**Comment by sindresorhus** [comment]
See explanation in https://github.com/sindresorhus/conf/issues/92.

**Comment by AlyxMoon** [comment]
I've enjoyed this app, it was very easy to drop in and start to use.
This issue really stumped for for a moment before I dug into the functionality of `conf`. So I added a pull request for a small documentation change.

**Comment by sindresorhus** [comment]
Hmm, this is a bug. It should take the version of your project, not the electron-store version. `electron-store` needs to set the `projectVersion` to your apps version if not set. I think we can get it using https://www.electronjs.org/docs/api/app#appgetapppath and then reading the package.json.

**Comment by AlyxMoon** [comment]
Okay, I'll help with this then. I'll implement it as you suggested.

**Comment by Penggeor** [comment]
Encounter the same issue.
