### ISSUE TITLE
Accessing store from renderer

### ISSUE THREAD

**Issue by rwwagner90** [sindresorhus/electron-store#109]
I've been looking through issues about how to use the store in the renderer, and most issues say something like `just use it the same as you would in main`, but this is confusing to me. It appears the store is not a singleton, so if you set it up in main, there is no way to access the same store in the renderer, correct?

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-store/issues/15 (And yes, I need to get that documented in the readme)

**Comment by rwwagner90** [comment]
@sindresorhus I would recommend documenting something like this for accessing store values from the renderer:

```js
ipcMain.on('requestStoreValue', (event, key) => {
  event.sender.send('replyStoreValue', key, store.get(key));
});
```

**Comment by sindresorhus** [comment]
Agreed. Especially important as Electron plans to deprecate the `remote` module (`remote.require`).

**Comment by rwwagner90** [comment]
@sindresorhus would you like me to try to throw together a PR?

**Comment by sindresorhus** [comment]
@rwwagner90 That would be great. Would be best to show usage with the `.invoke/`.handle` APIs as they simplify this kind of communication: https://www.electronjs.org/docs/api/ipc-main#ipcmainhandlechannel-listener

**Comment by rwwagner90** [comment]
@sindresorhus I opened a PR. Please let me know if you would like any changes to the content!

**Comment by jeoy** [comment]
@sindresorhus  I just found out I can set in Main process and directly get in renderer process, but why since you mentioned it's not a singleton.

```js
// mainProcess.js
import Store from 'electron-store';
const store = new Store();

store.set('foo',  'bar');

```
```js
// renderer.js

config.get('foo');
//=> 'bar'
```
