### ISSUE TITLE
Question: does store.get() read the file or uses an internal copy of the content in memory

### ISSUE THREAD

**Issue by DRocksCoding** [sindresorhus/electron-store#113]
Hello and thanks a lot for the work you put in this module it's very useful and reliable.

I'm a self taught hobbyist so this might be a stupid question but,
I was wondering if you could clarify what happens when you use store.get(key)?

Right now when I start my electron app, I load the store content in a separate javascript object (appData.key) so that when I need to get values I use memory instead of disk access. 
But does electron store itself keep an internal copy in memory so that using store.get() would not actually read the file?

Please tell me if I can improve the question and if otherwise you could enlighten me a bit.

Thanks in advance 
Alex

**Comment by sindresorhus** [comment]
It reads from disk. I would have liked to keep a copy in memory. The problem is that Electron has 2 or more processes (1 main process and n renderer processes), and keeping those in sync would be quite complicated. Users expect `.get()` to always give the correct up-to-date value.

**Comment by DRocksCoding** [comment]
Thanks for your reply. That's perfectly fine and a good thing I believe. 
But I wanted to make sure I was not keeping a copy of some data which already had a copy else where :)

I still have a sub question thats related to my original question...
Lets say I want to save and or get values from a store,  would wrapping the call inside an async function actually make it async or that would only add a layer of complexity without the added benefit?

**Comment by sindresorhus** [comment]
JavaScript is single-threaded. It would still be synchronous.
