### ISSUE TITLE
How do I write more efficiently?

### ISSUE THREAD

**Issue by dss886** [sindresorhus/electron-store#114]
I did not look at the source code carefully, and not very clear whether there is memory cache.
If I need to read and write frequently, which of the following methods is more efficient?

Case 1: 
```javascript
store.put("config.foo", "foo")
store.put("config.bar", "bar")
... // (lots of writing)
```

Or Case 2:
```javascript
const config = {};

config.foo = "foo";
config.bar = "bar";
... // (lots of writing)

store.put("config", config);
```

**Comment by sindresorhus** [comment]
Case 2 is more efficient. There's currently no memory cache or delayed writing, but that would indeed be nice.

**Comment by dss886** [comment]
thx

> Case 2 is more efficient. There's currently no memory cache or delayed writing, but that would indeed be nice.
