### ISSUE TITLE
Schema with array of objects

### ISSUE THREAD

**Issue by BotellaA** [sindresorhus/electron-store#115]
How would you validate an array of objects? I want to validate also the objects.
I am new to `ajv`, I did not find simple example doing this nested checking with `electron-store` or `conf`.

Thanks for your help

**Comment by vpaladino778** [comment]
@BotellaA How did you end up solving this?

**Comment by Zertz** [comment]
Here's a schema to get you started:

```js
const store = new Store({
  defaults: {
    unicorns: [],
  },
  schema: {
    unicorns: {
      type: "array",
      items: {
        type: "object",
        properties: {
          id: {
            type: "string",
          },
        },
        required: ["id"],
      },
    },
  },
});
```
