### ISSUE TITLE
Type error when setting `projectVersion` option

### ISSUE THREAD

**Issue by will-stone** [sindresorhus/electron-store#123]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/654103/83947467-ffa17000-a80e-11ea-9b57-71eddf1bd239.png">

PS thanks for Electron Store: invaluable tool in the Electron toolbox 🙂

**Comment by saydo17** [comment]
I was able to get around this by using a separate const for the config.
```
const options = {
  projectVersion: '0.1.1',
  ...other options here
}

export const store = new ElectronStore<Store>(options);
```

**Comment by Pettor** [comment]
The included types for ElectronStore even defines:
`type Options<T> = Except<ConfOptions<T>, 'configName' | 'projectName' | 'projectVersion' | 'projectSuffix'> & {`

So for some reason `projectVersion` is excluded from the options for electron-store which is based on `conf`. Not sure why but the above suggestion is a workaround for now.

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-store/pull/162#issuecomment-763041114
