### ISSUE TITLE
Question: Example for instance iteration in the readme

### ISSUE THREAD

**Issue by DRocksCoding** [sindresorhus/electron-store#124]
Hello and huge thanks for the module!

Could you please provide an example of this quote from the readme:
> The instance is iterable so you can use it directly in a for…of loop.

What could you do with that? I'm fairly new to JS btw so excuse my ignorance.

Thanks in advance

**Comment by sindresorhus** [comment]
https://www.google.no/search?q=javascript+iterable+for-loop&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari

**Comment by DRocksCoding** [comment]
> https://www.google.no/search?q=javascript+iterable+for-loop&ie=UTF-8&oe=UTF-8&hl=en-us&client=safari

Thanks...Obviously I read that before asking. As I said sorry for my lack of creativity with that iteration topic. I just dont see where you would use it. I thought you could show a simple scenario where you personnally would use the instance iteration feature.
Thanks for your quick reply.
