### ISSUE TITLE
How to set the range of electron-store?

### ISSUE THREAD

**Issue by samchenws** [sindresorhus/electron-store#128]
I open multiple identical programs and log in. The content stored in the electron-store will be covered. How can I solve this problem? thank you

**Comment by sindresorhus** [comment]
It's not clear what you're asking. What do you mean by "covered"?

**Comment by samchenws** [comment]
Sorry, English is not very good
![image](https://user-images.githubusercontent.com/37535153/87013004-99887e00-c1fc-11ea-96ef-e4780f675894.png)

**Comment by sindresorhus** [comment]
You would usually not want to allow this as at complicates everything. macOS prevents multiple instances running at the same time by default. On Windows and Linux, you can use this API: https://github.com/electron/electron/blob/master/docs/api/app.md#apprequestsingleinstancelock

You can see it in action here: https://github.com/sindresorhus/caprine/blob/3583346e146a9bff5c1b1559b600f2aafb2160a1/source/index.ts#L78-L90

If you really want to allow multiple instances, it's up to you to handle this. You could either add a unique prefix to the `uinfo` key or use different config files.

**Comment by samchenws** [comment]
thanks
