### ISSUE TITLE
[feature] possibility to set config file location

### ISSUE THREAD

**Issue by vorthess** [sindresorhus/electron-store#13]
Your lib looks perfect to me, but I need possibility to set where config should be saved (basically app is for devs and i need some .rc file in ~ so it can persist after update & allow someone to edit it quickly). Is it hard to make?
Also it could be nice if I can pass json object in a store constructor as a first state, so I can actually manually sync data to file as a "backup" config

**Comment by sindresorhus** [comment]
> so it can persist after update & allow someone to edit it quickly

The config is stored outside the app, so it's already persisted through updates.

> Also it could be nice if I can pass json object in a store constructor as a first state

See the `defaults` option.

**Comment by sindresorhus** [comment]
You can now set the save location, although I would strongly urge you not to unless you really have to and know what you're doing. The default should work for 99% of use-cases.

https://github.com/sindresorhus/electron-store#cwd
