### ISSUE TITLE
Lint Error for use of '#Private' in index.d.ts (node modules)

### ISSUE THREAD

**Issue by Bindu-Patel-Dev** [sindresorhus/electron-store#134]
We are using "parser": "@typescript-eslint/parser" in our .eslintrc.json and so while compiling our electron code we are getting 

![image](https://user-images.githubusercontent.com/68999609/88925764-e516d080-d26c-11ea-8697-0564bca0d9a6.png)

We can get rid of this by adding  "parser": "babel-eslint" but it might create some issues in the way we want lint reports in our project.

It should work fine with both usage of lints.

Please suggest a better way of resolving it (it should be compatible to both).

**Comment by adamk33n3r** [comment]
Not the same exact error but caused by the same part of code

![image](https://user-images.githubusercontent.com/1350444/89427444-3e697e80-d709-11ea-95b0-5667e9d04fef.png)

I need to be targeting `es5` as far as I can tell so I don't know what I'm supposed to do about the error.

**Comment by VolanDeVovan** [comment]
Same error
Using with cra

**Comment by sindresorhus** [comment]
You need to upgrade TypeScript version.

**Comment by zlq4863947** [comment]
After downgrading to 5.2.0, solve this problem

**Comment by lucasltv** [comment]
Same error here... =(
