### ISSUE TITLE
Not support electron 10

### ISSUE THREAD

**Issue by Nannny** [sindresorhus/electron-store#139]
![image](https://user-images.githubusercontent.com/46217211/91689412-a7240980-eb96-11ea-8807-3a775631b6c4.png)
![image](https://user-images.githubusercontent.com/46217211/91689452-bacf7000-eb96-11ea-80d9-a1bca24f9243.png)

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/electron-store/commit/5486aa5ad821d6388419eb628256451f7e234c6a

**Comment by thamara** [comment]
Hi @sindresorhus, I'm upgrading my application which uses electron-store, and even though I'm specifying `enableRemoteModule` when creating my BrowserWindow I'm still hitting the issue of `TypeError: Cannot read property 'app' of undefined` inside electron-store.
Do you have any idea what might be missing?
Thank you so much!

**Comment by GiovanH** [comment]
@sindresorhus I am also experiencing this same issue on Electron 10 even with `enableRemoteModule` explicitly set to true on all my browserwindows and webviews.
