### ISSUE TITLE
Observe config

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-store#14]
I think it could be useful to be able to observe changes. I like how it's done in Atom.

Previous art:
- https://atom.io/docs/api/v1.0.0/Config
- https://github.com/nathanbuchar/electron-settings/wiki/API-documentation#watch

**Comment by andreasjacobsen93** [comment]
It could also be something like the electron-json-storage:
```
storage.get('foobar', function(error, data) {
  if (error) throw error;

  console.log(data);
});
```

**Comment by sindresorhus** [comment]
@andreasjacobsen93 Your example is just an async version of the `get` method. That's not what this issue is about.

**Comment by callodacity** [comment]
@sindresorhus did you want this to be added into `electron-store` or the upstream `conf` module?

**Comment by sindresorhus** [comment]
@callodacity `conf`

**Comment by callodacity** [comment]
@sindresorhus okay, I'll draft a PR at some point 👍
