### ISSUE TITLE
How to deal with encryptionKey changes as migration?

### ISSUE THREAD

**Issue by iamisti** [sindresorhus/electron-store#144]
Is there a way to transition from a state where encryptionKey A was used, and we want to move to encriptionKey B?

**Comment by sindresorhus** [comment]
You have to wait for the user to put in their password (decrypt the encryptionKey) and then when you save again (encrypt), use the new key. If you're in the control of the key, you could probably do it automatically at launch (set a flag when it's done so you don't do it multiple times).
