### ISSUE TITLE
Option to save minified JSON

### ISSUE THREAD

**Issue by RvNovae** [sindresorhus/electron-store#145]
I was wondering if it is possible to save minified JSON in order to save space.

If it isn't, is this a feature that could be added?

**Comment by sindresorhus** [comment]
If minifying the JSON matters, you're probably saving too much to the store.

What is the size of your store?

**Comment by RvNovae** [comment]
I was just curious.
Totally agree with you. Should probably use something else in such a case.
Thank you for your switft answer though!

**Comment by sindresorhus** [comment]
I cannot imagine it would make much difference regardless. Even if you added lots of data, the savings would be close to nothing compared to the size of the app.
