### ISSUE TITLE
Issue with ES5 target in 6.0.1

### ISSUE THREAD

**Issue by Dawar** [sindresorhus/electron-store#146]
Having an issue with targeting ES5 with this package. Last version that works is 5.2.0

ERROR in node_modules/conf/dist/source/index.d.ts:5:5 Private identifiers are only available when targeting ECMAScript 2015 and higher.

**Comment by sindresorhus** [comment]
This is a package for Electron and Electron supports ES2015. ES5 output is not supported.

**Comment by SolarIceMedia** [comment]
whether Electron supports es2015 or not, not all front end frameworks do. Angular for example compiles to es5 still to support all browsers. so maybe it should support es5 ?

**Comment by Dawar** [comment]
> whether Electron supports es2015 or not, not all front end frameworks do. Angular for example compiles to es5 still to support all browsers. so maybe it should support es5 ?

This is exactly what I was thinking. Doesn't really seem like private identifiers are all that necessary in the context anyway. If you can support a multitude more projects with such a trivial change maybe we should consider it?

**Comment by RHeynsZa** [comment]
> whether Electron supports es2015 or not, not all front end frameworks do. Angular for example compiles to es5 still to support all browsers. so maybe it should support es5 ?

But you don't need to support all browsers, you're running electron which is running chromium

**Comment by kunokdev** [comment]
Due to this issue this library is basically not usable after version:  5.2.0
