### ISSUE TITLE
How can I force electron-store to force Windows line ends (CR+LF) when saving?

### ISSUE THREAD

**Issue by alexbfree** [sindresorhus/electron-store#147]
Hi @sindresorhus - For a multi platform app I need to guarantee CR+LF line ends (as opposed to Unix style LF only) each time the electron store is saved. Is there some way I can specify this as an option? Thanks.

**Comment by sindresorhus** [comment]
No, there's no way to do that and I don't think I want to add an option for it either. There's really no good reason to use CRLF. Windows supports LF fine.

**Comment by alexbfree** [comment]
@sindresorhus OK, in that case i would ask a different question:

Is there any way I can reliably and predictably tell whether the output file from electron-store will be CR+LF or LF? And will this be the same in all circumstances across all platforms?

**Comment by sindresorhus** [comment]
It will always store as LF.

**Comment by alexbfree** [comment]
Thank you.
