### ISSUE TITLE
Remove remote module

### ISSUE THREAD

**Issue by dragonDScript** [sindresorhus/electron-store#148]
Hey, so I'm writing this because in newer electron versions the `remote` module is being deprecated.
Due to this, major packages like Fiddle are now using IPC.
Why wouldn't you do this with store? I'm having problems with this because I can't use remote in the preload.js

**Comment by sindresorhus** [comment]
I welcome good PRs for this. I don't use Electron myself anymore, so it's not something I plan on working on.

To solve this, we have to set up synchronous communication for the renderer to fetch the user path from the main process.

**Comment by dragonDScript** [comment]
Okay, so I will do a PR. Thank you. (Also, for people that've googled this, the PR will be mentioned above)
