### ISSUE TITLE
Remote will be deprecated, Electron-store relies on remote

### ISSUE THREAD

**Issue by LaserYGD** [sindresorhus/electron-store#152]
Remote will be deprecated in version 12, and completely removed in electron 14. 
While it's not right around the corner, it's not too far away. Seeing how this library relies on Remote to be usable in the renderer (as far as I know), I thought I'd post this issue. 

Although it won't be in electron, I do believe you'll be able to use Remote as a library, but I'm not sure.
For more information, check https://github.com/electron/electron/issues/21408

**Comment by sindresorhus** [comment]
We should move to send the `userData` directory over IPC. This will mean we need to force the user to call an initialization method (that sets up the IPC endpoint) in the main process before the renderer API can be used.

I don't plan to work on this as I'm not using Electron much anymore, but a good pull request is welcome.
