### ISSUE TITLE
electron-store can`t set value global?

### ISSUE THREAD

**Issue by yyccQQu** [sindresorhus/electron-store#158]
```
const userSchema = {
	userInfo: {
		type: "object",
	},
	token: {
		type: "string",
	},
	chatInRooms: {
		type: "array",
	},
	// [usersId]:{
	//  chatInRooms: chatInRooms
	// 	chatLocalMsg: {
	// 		[roomIdAndId]: [...list],
	// 	},
	// }
};
export const userStore = new Store({ userSchema });

```
![image](https://user-images.githubusercontent.com/32674176/103215219-30243500-492c-11eb-9fa2-b5aa15a18301.png)

when i use 
```
userStore.set('RC_168.chatLocalMsg.173_1',[])
```
He is still the original value, his value only changed at that time. When the value was retrieved, he did not change at all.
When the value is obtained based on the key again, the value has not changed

**Comment by sindresorhus** [comment]
`electron-store` has no option called `userSchema`. I'm also not sure what you're asking.

**Comment by yyccQQu** [comment]
> `electron-store` has no option called `userSchema`. I'm also not sure what you're asking.

```
userStore.set('RC_168.chatLocalMsg.173_1',[])
=> 
userStore.get('RC_168.chatLocalMsg.173_1') = []
==> Re-request elsewhere
userStore.store.get("RC_168") ==> Still the original value [1,2,3,4,5]
```

**Comment by yyccQQu** [comment]
> `electron-store` has no option called `userSchema`. I'm also not sure what you're asking.

I see  your document~ could do this...... but After more nesting levels, the key value inside cannot be manipulated。
I can only use localstorage。。。
```
schema
type: object

JSON Schema to validate your config data.

Under the hood, the JSON Schema validator ajv is used to validate your config. We use JSON Schema draft-07 and support all validation keywords and formats.

You should define your schema as an object where each key is the name of your data's property and each value is a JSON schema used to validate that property. See more here.
```

**Comment by yyccQQu** [comment]
So sorry. It`s my code bug~~~.
colud use `Deep nested schema`.
