### ISSUE TITLE
get error in 7.0.1 Cannot destructure property 'defaultCwd' of 'ipcRenderer.sendSync(...)' as it is undefine

### ISSUE THREAD

**Issue by szw12asd** [sindresorhus/electron-store#164]
after update electron-store to v7.0.1 ,i got the error like
![image](https://user-images.githubusercontent.com/14155172/107112203-d26efb00-6890-11eb-96d0-1cf0d5214819.png)
while revert to v6.0.1 it is ok
electron version:11.2.0
here is my webReference:
![image](https://user-images.githubusercontent.com/14155172/107112275-50330680-6891-11eb-9749-0dbfaafed6c7.png)

**Comment by sindresorhus** [comment]
// @MehediH

**Comment by MBearo** [comment]
Try call Store.initRenderer() in the main process?

**Comment by szw12asd** [comment]
> Try call Store.initRenderer() in the main process?

useful,thanks

**Comment by sindresorhus** [comment]
We need a better error message for this case.
