### ISSUE TITLE
Update conf dependency to 9.0.2

### ISSUE THREAD

**Issue by lnovelli** [sindresorhus/electron-store#167]
I just noticed that the ajv-formats [issue](https://github.com/sindresorhus/conf/issues/140) was solved on the "conf" repository with [version 9.0.2](https://github.com/sindresorhus/conf/releases/tag/v9.0.2) =)
Is it possible to update "conf" dependency in package.json to version 9.0.2 to include that change? It is now using version 9.0.0.
Many thanks!

**Comment by sindresorhus** [comment]
This is not needed. Semver handles this for us. Read more here: https://nodesource.com/blog/semver-tilde-and-caret

Just reinstall `electron-store` and get the latest version.
