### ISSUE TITLE
Question: Can stores be using across multiple files?

### ISSUE THREAD

**Issue by sinmineryt** [sindresorhus/electron-store#169]
I'm asking if I can use stores across multiple files like this:

**one.js**
```js
const Store = require('electron-store');
const store = new Store();

store.set('unicorn', '🦄');
```
**two.js**
```js
const Store = require('electron-store');
const store = new Store();

var unicorn = store.get('unicorn');
console.log(unicorn); // => 🦄
```

or will it create two seperate stores?

**Comment by sindresorhus** [comment]
It's possible if both the constructors receive the exact same options, but it's not recommended. Instead, create a `store.js` file, setup the store there and import that file into `one.js` and `two.js`.

https://github.com/sindresorhus/electron-store/issues/15
