### ISSUE TITLE
Question: Does this plugin directly persists standard data ? Like cache / localstorage / cookies ?

### ISSUE THREAD

**Issue by Aarbel** [sindresorhus/electron-store#175]
# Does this plugin directly persists standard browser data ? Like cache / localstorage / cookies ?

Opening a new window or re-opening my app doesn't store basic storage data (a bundle.js file and few localstorage keys)

Thanks a lot for your help

**Comment by sindresorhus** [comment]
No. This package only stores what you manually store yourself. It's all in the docs.
