### ISSUE TITLE
ElectronStore path different when called in main and renderer threads

### ISSUE THREAD

**Issue by kmturley** [sindresorhus/electron-store#181]
Using Electron and Next.js getting two different config paths when calling the same store from different files/threads:
```
/Users/username/Library/Application Support/AppName/config.json
/Users/username/Library/Preferences/electron-store-nodejs/config.json
```

/electron-src/store.ts
```TSX
export const store = new ElectronStore();
```

/renderer/pages/projects/index.tsx
```TSX
import { store } from '../../../electron-src/store';

// Fetch data at build time.
export const getStaticProps: GetStaticProps = async () => {
  // /Users/username/Library/Application Support/AppName/config.json
  console.log('getStaticProps', store.path);
}
```

/renderer/pages/projects/[slug].tsx
```TSX
import { store } from '../../../electron-src/store';

// Specify dynamic routes to pre-render pages based on data.
export const getStaticPaths: GetStaticPaths = async () => {
  // /Users/username/Library/Preferences/electron-store-nodejs/config.json
  console.log('getStaticPaths', store.path);
}
```

Overriding the default path logic fixes the issue e.g.

/electron-src/store.ts
```TSX
export const store = new ElectronStore({ cwd: process.cwd() });
```

Full project source code is here:
https://github.com/studiorack/studiorack-app

**Comment by sindresorhus** [comment]
// @rroessler @MehediH

**Comment by rroessler** [comment]
@kmturley Looking at your project my guess is that as you are building the renderer for Next.js seperate to the Electron process, then `app.getPath()` from our side will return different paths. 

However by instead forcing state with `cwd: process.cwd()` this appears to correct itself. Regardless, this is a context problem from `app.getPath()`. The solution to this might be to directly create a path manually. As a brief example (proper paths would need to be determined):

```javascript
const userDataPath = process.env.APPDATA 
        || (process.platform == 'darwin' 
            ? process.env.HOME + '/Library/Application Support' 
            : process.env.HOME + "/.local/share") + "/" + app.getName();
```

This should alleviate context issues, but very much dependent on what the repo owner says. As a simpler solution however, setting the default as `process.cwd()` might also be viable.

**Comment by kmturley** [comment]
I think you are correct. When I log out the two functions:

```TSX
console.log('getStaticProps', store.path);
console.log('getStaticProps process', process.execPath);

// getStaticPaths /Users/username/Library/Preferences/electron-store-nodejs/config.json
// getStaticPaths process /usr/local/Cellar/node/14.4.0/bin/node

console.log('getStaticPaths', store.path);
console.log('getStaticPaths process', process.execPath);

// getStaticPaths /Users/username/Library/Preferences/electron-store-nodejs/config.json
// getStaticPaths process /Users/username/Sites/studiorack-app/node_modules/electron/dist/Electron.app/Contents/Frameworks/Electron Helper.app/Contents/MacOS/Electron Helper
```

So even though they import the same ElectronStore from the same file, they are being run in completely different ways.

So this is not your bug, just my confusion on how it's run :)
