### ISSUE TITLE
Deleting a created store.

### ISSUE THREAD

**Issue by snaildos** [sindresorhus/electron-store#189]
new Store({ creates a new store. How can I delete a store?
Regards,
SnailDOS

**Comment by sindresorhus** [comment]
If you just want to clear the store, you can use `.clear()`. If you really need to delete the actual file, you can use `fs.unlinkSync(store.path)`.

**Comment by snaildos** [comment]
I really just want to change the encryption password. Would clear reset the enc password?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by snaildos** [comment]
Resolved. Deleting the file works.

**Comment by NickDiMucci** [comment]
I'm also trying to change the encryption key but am running into problems. My original idea was to load the existing store with the existing encryption key, obtain reference to `const oldStoreObj = oldStore.store` to get a JSON object of the current store, create a new store with the new encryption key and set `newStore.store = oldStoreObj`. While that does correctly load the old configurations into the new store, it doesn't seem to be writing them to the new config.json file. On subsequent reloads of the new config.json with the new encryption key, `newStore.store` doesn't have any of the previously set configurations. 

Any ideas on how I can update the encryption key?
