### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/electron-store#19]
Would be useful to have forward migration support built-in. You define the version when something changed and a function where you can manipulate the store and the correct migrations will be applied according to the installed version on the first run after an update.

Quick braindump API:

```js
const Store = require('electron-store');

const migrations = {
	'1.0.0': store => {
		const old = store.get('old');
		store.set('new', old);
		store.delete('old');
	}
};

const store = new Store({migrations});
```

I'm open to feedback.

**Comment by kounelios13** [comment]
That would be great

**Comment by trodi** [comment]
An electron app may have multiple types of files that have to be migrated (e.g., sqlite db, `electron-store`, user save/export files). Would it not be better to use one migration module which can be configured to handle each of your cases and avoid reinventing the wheel for `electron-store`?

I'm currently implementing support for the above context and evaluating packages such as [umzug](https://github.com/sequelize/umzug/) and [migrate](https://github.com/tj/node-migrate) as a way to have a consistent migration API across the app. This appears to be a better option than unique migration APIs for each data store type. This would also allow if someday you must migrate away from `electron-store` to a completely different format.

**Comment by sindresorhus** [comment]
@trodi If you're using multiple storage solutions, sure, but in all the apps I've made, this one has been enough, and I just want an easy built-in way to do migrations for my config. The generic migrations modules are too unopinionated for my needs.

**Comment by trodi** [comment]
@sindresorhus That's a fair point and will be sufficient for many use cases. Hopefully, this package will be able to take advantage of lessons learned from other packages have had to solve this issue.

P.S. - Thanks for a great package 😄.

**Comment by morajabi** [comment]
@sindresorhus How's it going? If it's easy I can give it a hand.
