### ISSUE TITLE
It creates multiple files not in `app.getPath('userData')`

### ISSUE THREAD

**Issue by pacexy** [sindresorhus/electron-store#192]
My code: `const storage = new Storage({
  name: 'state',
})`

And it create 2 files:
1. %APPDATA%/electron-store-nodejs/Config
2. %APPDATA%/[my-app-name]-nodejs/Config/state.json

Expect:
%APPDATA%/[my-app-name]/state.json

**Comment by sindresorhus** [comment]
Can you confirm that you're on the latest `electron-store` version? Are you using `electron-store` from the main process or renderer process?

**Comment by pacexy** [comment]
> Can you confirm that you're on the latest `electron-store` version? Are you using `electron-store` from the main process or renderer process?

Thanks for the reply, I tried to create an instance in the main process, and the problem was solved.
