### ISSUE TITLE
When I configure the migration rule "> = 3.2.0", the data is not initialized

### ISSUE THREAD

**Issue by qhanw** [sindresorhus/electron-store#193]
When I configure the migration rule "> = 3.2.0", the data is not initialized
![image](https://user-images.githubusercontent.com/10607656/123950540-61aeb380-d9d6-11eb-93a6-1a8c2a0bc4ff.png)

**Comment by alex-drocks** [comment]
Was it already initialized? look manually in the json file if the migration key already exist and has the 3.2.0 version defined. Migration only works once.

Also, make sure that your Electron App Version is set to 3.2.0 or greater.

**Comment by qhanw** [comment]
The problem has been solved. Indeed, as you said, "migration only works once", I misunderstood it before!
Thanks!
