### ISSUE TITLE
Using store with redux

### ISSUE THREAD

**Issue by skbolton** [sindresorhus/electron-store#20]
I am using electron-store to re-hydrate the state of my redux store on app load. I am noticing that the setters and getters on store properties are showing up in my redux store. Is there an easy way to get values out of the store as properties that way I can keep my store pure and serializable?

I know that I can `JSON.stringify()` and then `JSON.parse()` to get rid of the getters and setters but that seems kind of inefficient? Any help on answering this would be appreciated!

**Comment by skbolton** [comment]
Here is a photo showing what I am talking about. This is a redux-logger output of my store.
<img width="788" alt="screen shot 2017-07-11 at 2 41 30 pm" src="https://user-images.githubusercontent.com/13260877/28089730-2bc38450-6647-11e7-8519-5f0724c7ad09.png">

**Comment by SamVerschueren** [comment]
To me, it looks like the getters and setters where added by you, not by this module... Or am I missing something here?

**Comment by skbolton** [comment]
No the settings object is what I got back from reading from `electron-store`

**Comment by skbolton** [comment]
This is my wrapper around electron-store
```
getSettings () {
  return this.store.get('settings')
}
```
This is me using the wrapper and configuring the store
```
const cache = remote.require('./cache')
const settings = cache.getSettings()
const api = new API()

export default () => {
  return createStore(
    rootReducer,
    { settings },
    applyMiddleware(thunk.withExtraArgument(api), logger)
  )
}
```

**Comment by sindresorhus** [comment]
Hmm, maybe those setter/getters are added by `remote.require`.

**Comment by kevva** [comment]
> Hmm, maybe those setter/getters are added by remote.require.

Yes, looks like these lines are doing it https://github.com/electron/electron/blob/master/lib/renderer/api/remote.js#L259-L262.

**Comment by sindresorhus** [comment]
Closing as this is just how `remote.require` works. FYI though, you can just import `electron-store` directly in the renderer process. You don't have to use `remote.require`.

**Comment by jasonzhouu** [comment]
I can import `electron-store` only if set `nodeIntegration: true` when create `BrowserWindow`
