### ISSUE TITLE
Different electron store path when executing electron in webpack before() hook and executing electron script in package.json

### ISSUE THREAD

**Issue by HwangTaehyun** [sindresorhus/electron-store#204]
My electron app name is 'Swift'. Electron-store would get app name from package.json's app name and set electron store path like (~/Library/Application\ Support/Swift/config.json) in Mac.

However, when I execute electron in webpack before hook, electron store path becomes (~/Library/Application\ Support/Electron/config.json) in Mac.

```js
module.exports = {
  mode: 'development',
  entry: {
    index: './src/renderer/index.tsx',
  },
  target: 'electron-renderer',
  devtool: 'source-map',
  devServer: {
    contentBase: path.join(__dirname, OUT_DIR, 'index.js'),
    compress: true,
    hot: true,
    disableHostCheck: true,
    port: 9000,
    historyApiFallback: true,
    stats: {
      errorDetails: true,
    },
    before() {
      if (process.env.START_HOT) {
        console.log('Starting main process');
        spawn('yarn', ['start-main-dev-in-react'], {
          shell: true,
          env: process.env,
          stdio: 'inherit',
        })
          .on('close', (code) => process.exit(code))
          .on('error', (spawnError) => console.error(spawnError));
      }
    },
  }
...
}
```

**yarn start-main-dev-in-react** script in package.json
```js
    "start-main-dev_in_react": "webpack --mode development --config webpack.electron.main.js && electron --inspect-brk=5858 ./build/main/main.js"
```
Why does this happen?

My electron version is 15.1.0 and electron-store version is 8.0.0

**Comment by sindresorhus** [comment]
We are just using the Electron API: `app.getPath('userData')`. If it returns the incorrect value, I recommend opening an issue on https://github.com/electron/electron
