### ISSUE TITLE
Data loss when the app is quit forcefully or when app stops working unexpectedly.

### ISSUE THREAD

**Issue by rishabh1403** [sindresorhus/electron-store#21]
Been using this module for a while, and working great. But data loss occurs when the app hangs or is quit forcefully. Any workaround or solutions for the issue ?

**Comment by Silexstudio** [comment]
I'm having the same issue, although it happens like 1% of the time it's still annoying.
I fixed it by making a backup everytime I start my app or at specific stages, if the app crashes then I check if the store is erased at start, then load the backup.

**Comment by rishabh1403** [comment]
Actually it happens only when app crashes **and** file was open at that point for reading or writing.
I fixed it by making sure that I read only once from the file. When app starts I read the file and save the contents in a variable and pass those values as events between renderer and main processes while the app runs.

**Comment by sindresorhus** [comment]
This should be fixed now. It now writes new config to disk atomically, so if the process crashes during write, it's just a temp file that gets corrupted, not the config file itself. Just reinstall electron-store and you'll have [the change](https://github.com/sindresorhus/conf/commit/7d07c5dd43ab84f3887b50355bc899d8d4528cba).

**Comment by rishabh1403** [comment]
@sindresorhus Thanks a lot 👍  will give a try.
