### ISSUE TITLE
Unable to load in renderer, Electron 12+

### ISSUE THREAD

**Issue by jessedp** [sindresorhus/electron-store#210]
In upgrading a larger app from Electron 8 to Electron 12+, I've become unable to load electron-store. The two errors I've received have been `Uncaught ReferenceError: __dirname is not defined` and  `Uncaught ReferenceError: process is not defined` (with the [path](https://www.npmjs.com/package/path) module).

[This commit](https://github.com/jessedp/test-webpack/commit/7eb9b5703f7fc832b0566ffc06cb70a7b57de969) shows the basic test - init in the main process, attempt to access in the renderer process.

Whatever #198 was trying to report about *contextIsolation* could be related to this ... which I mostly mention because this problem starts with Electron 12 (continues into 16) and - since it was mentioned there - using `nodeIntegration: true` in webPreferences for any of these tests makes no difference.

I kind of feel like I've either missed something obvious or this is an Electron issue.

**EDIT**:  Oh, I think this needs to somehow use *contextBridge* 

### Reproductions:

All of these use:
* Node 16.13.1
* Electron 16+ (vite was quick, so I tested the stables of Electron 12-16 )

*Uncaught ReferenceError: __dirname is not defined*

* vite-electron-builder - vite+vue - https://github.com/jessedp/test-vite

```
Uncaught ReferenceError: __dirname is not defined
    at node_modules/electron/index.js (index.js:4)
    at __require2 (chunk-EABY2BFN.js?v=68b2cb79:32)
    at node_modules/electron-store/index.js (index.js:3)
    at __require2 (chunk-EABY2BFN.js?v=68b2cb79:32)
    at dep:electron-store:1
```

* electron react boilerplate - webpack+react - https://github.com/jessedp/test-webpack

```
Uncaught ReferenceError: __dirname is not defined
    at Object../node_modules/electron/index.js (index.js:4)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/electron-store/index.js (index.js:3)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../src/renderer/App.tsx (App.tsx:2)
    at Object.options.factory (react refresh:6)
```

After insalling the `path` module...

*Uncaught ReferenceError: process is not defined*

* vite-electron-builder - vite+vue - https://github.com/jessedp/test-vite/tree/use-path

```
path.js:25 Uncaught ReferenceError: process is not defined
    at node_modules/path/path.js (path.js:25)
    at __require2 (chunk-EABY2BFN.js?v=627e1aec:32)
    at node_modules/electron-store/index.js (index.js:2)
    at __require2 (chunk-EABY2BFN.js?v=627e1aec:32)
    at dep:electron-store:1
```

* electron react boilerplate - webpack+react - https://github.com/jessedp/test-webpack/tree/try-branch

```
Uncaught ReferenceError: process is not defined
    at Object../node_modules/path/path.js (path.js:25)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../node_modules/electron-store/index.js (index.js:2)
    at Object.options.factory (react refresh:6)
    at __webpack_require__ (bootstrap:24)
    at fn (hot module replacement:61)
    at Object../src/renderer/App.tsx (App.tsx:2)
    at Object.options.factory (react refresh:6)
```

**Comment by bart** [comment]
Any updates on this?

**Comment by evilchis94** [comment]
I was able to solve this by following this [https://electron-react-boilerplate.js.org/docs/electron-store](url)

**Comment by bart** [comment]
Oh I will have a look, thank you very much @evilchis94 ! Appreciate it

**Comment by jessedp** [comment]
Thanks @evilchis94 - hopefully others will find this and realize that "works with electron 12+" means "works with electron 12+ if you proxy all of the calls you want".

**Comment by serg06** [comment]
I tried out @evilchis94 's solution, but it lead me down a crazy long path of trying to get `require('electron')` to work with `contextIsolation: true`.

I was able to resolve this issue, at least during development (I haven't tried a full build yet), with a different, albeit crazier, solution:

---

In BrowserWindow webPreferences, I set these options:

```
nodeIntegration: true,
contextIsolation: false,
```

Then in the vite.config.ts for my Renderer process, I changed the config from this (unrelated fields removed for brevity):

```js
export default defineConfig(() => ({
  build: {
    rollupOptions: {
      external: [...builtinModules.flatMap((p) => [p, `node:${p}`])],
    },
  },
}));
```

To this:

```js
import replace from '@rollup/plugin-replace';
import commonjsExternals from 'vite-plugin-commonjs-externals';

const custom_externals = ['electron'];

export default defineConfig(() => ({
  optimizeDeps: {
    // I don't know
    exclude: [...builtinModules, ...custom_externals],
  },
  plugins: [
    // Fix the mangled path that path.join() gets on renderer side
    replace({
        'path.txt': '../../../../path.txt',
        delimiters: ['', '']
    }),
    // I don't know
    commonjsExternals({
        externals: custom_externals,
    }),
  ],
  build: {
    rollupOptions: {
      // I don't know
      external: [...[...builtinModules, ...custom_externals].flatMap((p) => [p, `node:${p}`])],
    },
  },
}));
```

---

Extra context: My repo is based off of https://github.com/moodiest/vite-electron-builder-react.
