### ISSUE TITLE
WebContents #1 called ipcRenderer.sendSync() with 'electron-store-get-data' channel without listeners.

### ISSUE THREAD

**Issue by medi11** [sindresorhus/electron-store#212]
I keep getting this warning whenever I add  `electron-store`. Which leads to a frozen window.
**on frontend** 
```node
const Store = window.require("electron-store");
const store = new Store();
```
**on backend**
```node
    const mainWindow = new electron.BrowserWindow({
    title: "DOCTOR",
    show: false,
    webPreferences: {
		devTools: !app.isPackaged,
		nodeIntegration: true,
		contextIsolation: false,
		webSecurity: app.isPackaged,
	},
   });
```
electron: `^16.0.4`
electron-store: `^7.0.3`

**Comment by sindresorhus** [comment]
Try upgrading to the latest version.

**Comment by medi11** [comment]
It still the same, nothing changed.

**Comment by SStoliarchuk** [comment]
Can confirm this issue is present on latest version:
`"dependencies": {
	"electron-is-dev": "1.2.0",
	"electron-store": "8.0.1",
	"express": "4.17.1",
	"get-port": "5.1.1",
	"react": "17.0.2",
	"react-dom": "17.0.2"
}`

`const mw = new BrowserWindow({
	webPreferences: { 
		nodeIntegration: true,
		contextIsolation: false,
	},
});`

**Comment by SStoliarchuk** [comment]
@medi11 

In the main process, add these lines and it fixes the issue
```
const ElectronStore = require('electron-store');
ElectronStore.initRenderer();
```

**Comment by medi11** [comment]
> @medi11
> 
> In the main process, add these lines and it fixes the issue
> 
> ```
> const ElectronStore = require('electron-store');
> ElectronStore.initRenderer();
> ```

Thank you @SStoliarchuk, that fixed the issue.
