### ISSUE TITLE
Question: Is there a way to encrypt the data of electron store and use it?

### ISSUE THREAD

**Issue by prayag17** [sindresorhus/electron-store#217]

**Comment by sindresorhus** [comment]
The only way to safely do it is to let the user choose a password and encrypt/decrypt the data based on that. It's not something I plan to add built-in as different apps have different encryption needs, but I am open to adding hooks to allow this. For example, load and save hooks that receive the data and is expected to serialize/unserialize it.

**Comment by whitespacecode** [comment]
I managed to use the `serialize` and `deserialize` options in combination with [safeStorage from electron](https://www.electronjs.org/docs/latest/api/safe-storage) 

Would be great if you could make that an option ?
