### ISSUE TITLE
Setting url as key not working

### ISSUE THREAD

**Issue by JyotirmoyGoswami** [sindresorhus/electron-store#22]
```
const Store = require('electron-store');
const appStore = new Store();

var item = {
     "https://mail.google.com/mail/": { 
            "metadata": {
                    "name": default mail client"
              }
        }
};

appStore.set(item);
```

**Comment by sindresorhus** [comment]
How is it not working? What happens?

**Comment by JyotirmoyGoswami** [comment]
its storing like this :

`{
     "https://mail":{
            " google": {
                    "com/mail/": { 
                                 "metadata": {
                                           "name": default mail client"
                                   }
                        }
              }
        }
}`

**Comment by sindresorhus** [comment]
From the docs:

> You can use dot-notation in a key to access nested properties.

I guess it could make sense to introduce an option to disable that.

**Comment by kevva** [comment]
> I guess it could make sense to introduce an option to disable that.

Probably. Downside is that you wouldn't be able to use it then even if you just wanted to disable it for one key.

@JyotirmoyGoswami, for now you can escape your dots like `\\.`.

**Comment by purplekrayons** [comment]
I encountered this issue storing usernames as keys (which can contain period characters).

I used some regex to escape:

`var string = string.replace(/\./g, '\\.')`

**Comment by cdekok** [comment]
Perhaps an escape method could be added to the class for convenience?

**Comment by kevva** [comment]
> I guess it could make sense to introduce an option to disable that.

Either that, or adding an option to the `set` method as suggested by @sindresorhus above.

**Comment by Spring3** [comment]
You could also base64 encode it
