### ISSUE TITLE
Module not found: Can't resolve 'path'

### ISSUE THREAD

**Issue by Bosskee** [sindresorhus/electron-store#221]
Hello. I'm having problems using this library. Desired functionality for me is to simply store a json on disk that can be accessed in renderer(App.js for example).

`main/main.ts`:
```
const Store = require('electron-store');
Store.initRenderer();
```

`renderer/App.js`:
```
const Store = require('electron-store');
const store = new Store();
```

This results in the following error:

> Module not found: Can't resolve 'path' in 'C:\Users\User\Desktop\React\ProjectName\node_modules\atomically\dist'
> node_modules/atomically/dist/index.js

Any ideas on this? Thankful for any input!

**Comment by sindresorhus** [comment]
This is a problem with your build configuration, not this package.

**Comment by Bosskee** [comment]
Ok. I used [Electron React Boilerplate](https://electron-react-boilerplate.js.org/) for my project.

**Comment by Bosskee** [comment]
Found this:
https://electron-react-boilerplate.js.org/docs/electron-store/

**Comment by ackmanx** [comment]
> Found this: https://electron-react-boilerplate.js.org/docs/electron-store/

Awesome, thanks for the follow-up and link. I'm using create-react-app with Electron and importing this package throws errors about webpack 5 and polyfills and using the link's guidance solved it.

**Comment by marcjulianfleck** [comment]
Any other solution to this issue? How to avoid setting up the own IPC handlers when using React for example?
