### ISSUE TITLE
Calling `new Store`  throws Dynamic require error

### ISSUE THREAD

**Issue by Seanmclem** [sindresorhus/electron-store#226]
When I 

`import Store from 'electron-store';`

And add the line 

`const store = new Store();`

I get the error 

`Dynamic require of "path" is not supported`

And my app does not work. 

`"electron-store": "^8.0.1",`
`"electron": "^17.1.2",`

**Comment by sindresorhus** [comment]
This is sounds like a problem with your build tool or its config.

**Comment by Seanmclem** [comment]
> This is sounds like a problem with your build tool or its config.

probably, it happened with another storage lib too. Any tips? The consensus from Google of "probably Vite" hasn't really helped much so far
