### ISSUE TITLE
Error: Cannot find module 'electron-store' in preload.js

### ISSUE THREAD

**Issue by Michael-py001** [sindresorhus/electron-store#228]
```js
const Store = require('electron-store');
const store = new Store();
```
i write above code in prolad.js.
In development environment, it work, but it run with error: `Cannot find module 'electron-store'` in production environment( i build an app), how can i fix it?

**Comment by sebi-alt** [comment]
Are you sure, you have included `nodeIntegration: true` in `webPreferences` when creating the BrowserWindow?
According to [the docs](https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts) only these few modules these available in the preload script:

- electron (only renderer process modules)
- [events](https://nodejs.org/api/events.html)
- [timers](https://nodejs.org/api/timers.html)
- [url](https://nodejs.org/api/url.html)

Hope this resolved your issue

**Comment by Michael-py001** [comment]
> Are you sure, you have included `nodeIntegration: true` in `webPreferences` when creating the BrowserWindow? According to [the docs](https://www.electronjs.org/docs/latest/tutorial/sandbox#preload-scripts) only these few modules these available in the preload script:
> 
> * electron (only renderer process modules)
> * [events](https://nodejs.org/api/events.html)
> * [timers](https://nodejs.org/api/timers.html)
> * [url](https://nodejs.org/api/url.html)
> 
> Hope this resolved your issue

Thank you so much!

**Comment by Eve-Sama** [comment]
It happens to me.

**Comment by Eve-Sama** [comment]
Therefor, we can not use `electron-store` in preload?

**Comment by dorakemon** [comment]
@Eve-Sama 
No, You can use electron-store in preload. 
And it is written here. 
https://electron-react-boilerplate.js.org/docs/electron-store
