### ISSUE TITLE
Override via ENV vars

### ISSUE THREAD

**Issue by rdamron** [sindresorhus/electron-store#23]
I think a great enhancement would be the ability to override values with env vars. This would give us the ability to use the store as the single source of truth in out app. Today in order to do this we will need to abstract out a layer and have an object as our single source of truth and load items into this object (either by electron-store or env vars). Because of this we lose the ability to listen to onChange events which is a fantastic feature of the library.

**Comment by kevva** [comment]
I'm not following why you need this. Could you describe a real use case? Environment variables usually have a very specific scope and are not meant to be used to store values in a config.

**Comment by rdamron** [comment]
I'm using this as a config store for remote digital displays. The requirements are that i have the ability to configure them via env var, flat file, and via menu. Env so that an admin can deploy them using powershell i believe.

It would also be handy as one of the config values is kiosk mode and during development its handy to have kiosk mode set to false which I've set via a config value passed from my package.json start script.

**Comment by kevva** [comment]
Feels a little out of scope for this module. If you really need it you should read the environment variables in your code and set the config values accordingly.

```
const foo = process.env.FOO;
store.set('foo', foo);
```

But yeah, environment variables isn't really *persistent values* so seems weird using them as so.

**Comment by rdamron** [comment]
You're right it isn't really about persisting its about temporarily overwriting them on boot.

I'm currently doing exactly as you say and I'm reading them and them setting them. Problem is that I now am persisting what i took in from the env to disk when i really just want to temporarily overwrite it.

**Comment by rdamron** [comment]
Then I'm storing state in a const and I'm not able to using nifty things like onChange. 

Perhaps i should open this in the conf library instead. 
Or find another module to store state. (Even though once started my state isn't very likely to change)

**Comment by kevva** [comment]
The `conf` library has the same principle as this and is meant for storing persistent data.
