### ISSUE TITLE
[BUG] missing TypeScript property beforeEachMigration inside ConfOptions

### ISSUE THREAD

**Issue by mtdvlpr** [sindresorhus/electron-store#231]
I want to use the beforeEachMigration function, but it hasn't been added to the type definitions yet. Please fix this!

**Comment by sindresorhus** [comment]
Try to reinstall `node_modules`. It shows for me.

<img width="1198" alt="Screen Shot 2022-07-30 at 13 47 04" src="https://user-images.githubusercontent.com/170270/181909490-3dbdc02a-bc56-4fde-9d3a-5d286ba7c672.png">

**Comment by mtdvlpr** [comment]
My bad, it's there now. Thanks!
