### ISSUE TITLE
Warning about not allowing union types

### ISSUE THREAD

**Issue by mtdvlpr** [sindresorhus/electron-store#232]
`Warning: strict mode: use allowUnionTypes to allow union type keyword at "#/properties/***/properties/***" (strictTypes)`

Hi, I'm getting above warning, because I set one of my properties to be either string or number. This warning can be traced back to the ajv package you use to validate the JSON schema. I would like the warning to be solved. Or is it against your wishes to allow the electron store to handle union types?

**Comment by sindresorhus** [comment]
Did you read https://ajv.js.org/strict-mode.html#union-types?

It seems it's preferable to use `anyOf`.

**Comment by mtdvlpr** [comment]
I have not, thanks!
