### ISSUE TITLE
Folders where electron store stores data

### ISSUE THREAD

**Issue by WebbyNFT** [sindresorhus/electron-store#233]
If I build electron app and use it it stores data in correct folder which is (on Mac)` ~/Library/Application Support/AppName/config.json`.

But when I use it in dev mode by running `yarn start` it also stores data somewhere but it is not the same folder because it does not update after changing some data even though I update it. Is there a different folder where it is stored for dev mode and after build or should it be the same one?

**Comment by sindresorhus** [comment]
This would be a question for the Electron project. This package just uses https://electronjs.org/docs/api/app#appgetpathname
