### ISSUE TITLE
Implement Web Storage API

### ISSUE THREAD

**Issue by achtan** [sindresorhus/electron-store#25]
https://developer.mozilla.org/en-US/docs/Web/API/Storage

**Comment by sindresorhus** [comment]
Are you requesting the API to be the same as the Web Storage API or that `electron-store` use the Web Store API underneath?

**Comment by achtan** [comment]
yes, just to implement the same api as Web Storage API, no need to use it directly...

**Comment by sindresorhus** [comment]
I don't really see the point. The current API is superior. If you really need this for some reason, just create your own wrapper module.
