### ISSUE TITLE
After quitting the app unexpectedly， not permitted, rename 'xxx/config.json.tmp-929aed' -> 'xxx/config.json'

### ISSUE THREAD

**Issue by liees** [sindresorhus/electron-store#254]
![image](https://user-images.githubusercontent.com/16377314/227817504-73bfbb05-c074-4f57-b559-489a95661232.png)

It can only be started normally after deleting the entire appdata/app

**Comment by liees** [comment]
"electron-store": {
      "version": "8.1.0",
      "resolved": "https://registry.npmmirror.com/electron-store/-/electron-store-8.1.0.tgz",
      "integrity": "sha512-2clHg/juMjOH0GT9cQ6qtmIvK183B39ZXR0bUoPwKwYHJsEF3quqyDzMFUAu+0OP8ijmN2CbPRAelhNbWUbzwA==",
      "requires": {
        "conf": "^10.2.0",
        "type-fest": "^2.17.0"
      }
    },

**Comment by liees** [comment]
```
"electron-store": {
      "version": "8.1.0",
      "resolved": "https://registry.npmmirror.com/electron-store/-/electron-store-8.1.0.tgz",
      "integrity": "sha512-2clHg/juMjOH0GT9cQ6qtmIvK183B39ZXR0bUoPwKwYHJsEF3quqyDzMFUAu+0OP8ijmN2CbPRAelhNbWUbzwA==",
      "requires": {
        "conf": "^10.2.0",
        "type-fest": "^2.17.0"
      }
    },
```

**Comment by liees** [comment]
electron: 13.6.9

**Comment by partap** [comment]
Just started seeing this as well...
![SCR-20230329-m59](https://user-images.githubusercontent.com/2281220/228678218-1e0a711c-541e-47a4-a63c-a748a0b410f7.png)

running...
electron-store: 8.1.0
Electron: 22.3.2
Windows 7

I'm using it to (among other things) save window positions for my app in handlers for "move" and "resize".  The handlers are debounced...but it does seem like it might be triggered by simultanous writes to the store file.

e.g. I have seen it happen when toggling my window fullscreen back and forth...or sometimes I get "lucky" and it is triggered immediately.  The app crashes to desktop after displaying that message, which is no bueno

**Comment by liees** [comment]
Looks like the author of this library is busy with other things~

**Comment by liees** [comment]
I am using rxdb now
