### ISSUE TITLE
Uncaught Exception: TypeError`Use delete() ` to clear values at ElectronStore.set

### ISSUE THREAD

**Issue by 2811267153** [sindresorhus/electron-store#255]
![image](https://user-images.githubusercontent.com/67245639/228357310-33bd7ada-346e-478d-a814-2f3732451c2c.png)
Hello, I'm sorry to bother you. I found an error when I was using this library today. As you can see in the specific error report, I want to save the user's historical music listening data in the main process, but, because I don't Determine whether the user has generated historical data before, so I need to delete the content saved by this parameter first, and then regenerate new content, but this error will appear when writing new data. I am not sure How did this problem arise, hope you can help me
![image](https://user-images.githubusercontent.com/67245639/228358384-978dc6e2-f8cc-497c-82a0-673738566994.png)

**Comment by sindresorhus** [comment]
You need to use the `delete()` method, not the delete keyword.

**Comment by 2811267153** [comment]
In fact, I used the`delete()`method at the beginning, but it still reported an error, which is why I used the `delete ` keyword, but it still reported an error
![image](https://user-images.githubusercontent.com/67245639/228425531-1f19a6e6-d2a1-4cbd-afb6-c0a5fddccaa2.png)

I encountered this exception twice last night. The first time was because I had a problem storing the data in songHistoryListData. I thought it was because the data I stored was too large, so I put it in my debugging code first. After clearing the list and storing the data, there is no error, but the list should be empty now, I don't know how this exception is triggered,

**Comment by Coldplayer1995** [comment]
This should not be closed had the same issue, and this is happening also when you try to set undefined value.

**Comment by arepp23** [comment]
+1 this happens when you try to set a boolean `false` value

**Comment by zprjk** [comment]
> This should not be closed had the same issue, and this is happening also when you try to set undefined value.

I got the same problem. Had to add a safeguard but error makes sense since electron-store uses json to store data, `undefined` is not a valid syntax in JSON. The error output mentioned above didn't help tho.
