### ISSUE TITLE
ENOENT: no such file or directory

### ISSUE THREAD

**Issue by iamisti** [sindresorhus/electron-store#258]
version:
"electron-store": "7.0.3",
"electron": "12.2.3",

We've been having an issue that only affects a small percentage of our users.

```
ENOENT: no such file or directory, open 'C:\Users\marti\Documents\MyFancyApp\userstate.json.tmp-4456844718a89bc9'
```

We dont understand why it happens. Upon debugging it with the user, the documents folder is there, the  "MyFanceApp" folder is there as well. 
It seems to have problems creating the tmp file, because even if we create the 'userstate.json' file manually, we still get the same error.
We've tried to run the applicaation with admission privileges, didnt help solving the issue. So the issue most likely not a permission issue.

Is there a way to avoid this or at least to handle the error? It brakes the whole application.

**Comment by sindresorhus** [comment]
The problem is with the https://github.com/fabiospampinato/atomically package (dependency of `conf` which is a dependency of `electron-store`). You should open an issue there instead.

**Comment by JuanIrache** [comment]
Even if this is not a problem within electron-store, does anyone know what triggers it and why it only affects some users? I have seen it with a Windows user with a number as his username, but the example above doesn't match that.
