### ISSUE TITLE
Encryption

### ISSUE THREAD

**Issue by purplekrayons** [sindresorhus/electron-store#26]
I've supplied an encryption key when creating a new store, but nothing happens. Could you please elaborate on whats required / how this works?

**Comment by sindresorhus** [comment]
What did you expect to happen and what didn't?

**Comment by purplekrayons** [comment]
That's a great question. The documentation doesn't really specify what, if anything, should happen and so I didn't expect anything to happen. Never-the-less, based on the documentation, I had guessed that I would open the .json store file and find the contents encrypted -- this was not the case.

`
var store = new Store({
	name: "myExample",
	encryptionKey: "oiV32mVp5lOwYneFESjrWq2xFByNOvNj"
})
`

**Comment by sindresorhus** [comment]
I'm not sure why you expected an empty store to produce an encrypted file. Just follow the usage example in the readme and you'll get your encrypted file.

**Comment by purplekrayons** [comment]
I'm not sure why you assume my store file is empty. Following the usage example does not result in an encrypted file, contrary to your assumption.

**Comment by purplekrayons** [comment]
Here is an example of a store file to help you visualize a non empty store:

{
    "this_is_a_key": "this_is_a_value"
}
