### ISSUE TITLE
The exception/error occurred when using electron-store in Vue 2.

### ISSUE THREAD

**Issue by aokleon** [sindresorhus/electron-store#260]
I tried to use electron-store in Vue 2, but encountered an error. Both my electron and electron-store packages are up to date. Here is an example of the error message.

![image](https://github.com/sindresorhus/electron-store/assets/62325709/730986ba-995c-4886-b7fe-6adf8c1c47af)

**Comment by sindresorhus** [comment]
This is a problem with your bundler or bundler config, not this package.
