### ISSUE TITLE
使用Electron-builder打包后运行程序，出现 require() of ES Module错误

### ISSUE THREAD

**Issue by nakeking** [sindresorhus/electron-store#262]
{
  "electron": "^25.1.0",
  "electron-builder": "^24.4.0",
  “electron-store”: "^8.1.0",
}
目前是在window环境打包出现该错误，mac没有尝试；

![image](https://github.com/sindresorhus/electron-store/assets/36540772/bdc48684-dba0-4150-a7a5-8408ac399550);

想请问是我webpack配置问题还是其他问题，希望有个方向;

**Comment by sindresorhus** [comment]
I don't see how this is relevant to this project. Also, please use English when opening issues on English projects.
