### ISSUE TITLE
Upgrade to latest conf

### ISSUE THREAD

**Issue by ArTiSTiX** [sindresorhus/electron-store#266]
Hello !

I am trying to use a fork of [conf](https://github.com/sindresorhus/conf) package (in order to test my changes before making a pull request), but `electron-store` still uses an outdated version of `conf`. Since `conf` is now using ESM, it requires some changes which makes the upgrade not-so-trivial.

I tried to do it, but i am loosing my mind, i don't know what i'm doing wrong in either my electron app, or in my changes, but when importing my own upgraded fork of `electron-store`, im having an error:

```Error [ERR_REQUIRE_ESM]: require() of ES Module L:\dev\ljas\midi-jar\node_modules\electron-store\index.js```

Here is my fork: https://github.com/la-jarre-a-son/electron-store/tree/upgrade-conf-esm

Could someone be of any help, i've seen some forks using latest conf, but no PR, and tests are not passing.

**Comment by ArTiSTiX** [comment]
I guess this is the same issue as for `dot-prop`, you wait for Electron to be ESM-friendly...

**Comment by iamterryclark** [comment]
I believe Electron have completed the PR on ESM. is it possible to now update electron-store?

**Comment by imkimchi** [comment]
did you find any workaround for this?

**Comment by Attiybom** [comment]
When I packaged and ran my program, I encountered the "conf module not found" issue. I think we might be facing the same problem, perhaps due to conf using ESM. I hope the official team can resolve this.

**Comment by npmstudy** [comment]
@sindresorhus the same issue. need a pr?
