### ISSUE TITLE
Cannot find module 'ajv/dist/compile/codegen'

### ISSUE THREAD

**Issue by shenxxu720** [sindresorhus/electron-store#275]
When I use the plugin in the test environment there is no problem, but the packaging formal environment prompt Cannot find module 'ajv/dist/compile/codegen', Using the electron-vite (https://electron-vite.org) build tool, what is the problem?

**Comment by npmstudy** [comment]
try this?

<img width="745" alt="image" src="https://github.com/sindresorhus/electron-store/assets/26357769/e2037efe-19bc-435e-a58e-865670392b0e">

**Comment by shenxxu720** [comment]
> try this?
> 
> <img alt="image" width="745" src="https://private-user-images.githubusercontent.com/26357769/326331631-e2037efe-19bc-435e-a58e-865670392b0e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzODY0NDksIm5iZiI6MTcxNDM4NjE0OSwicGF0aCI6Ii8yNjM1Nzc2OS8zMjYzMzE2MzEtZTIwMzdlZmUtMTliYy00MzVlLWE1OGUtODY1NjcwMzkyYjBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDEwMjIyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxZTJkZWIxYTc5YzlkMDZlNzQ4NGZiZmMzMTBhOGRhMTg4YTAzYjI1MDlmNTBiNGM3YmYzMzBiZjg5M2Q5NGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w3EhXJHG3QE9qjQSKO_2qTzBxhIp3wd0RilvoyvG4vQ">

You do need to install ajv into dependencies separately to solve this problem
![image](https://github.com/sindresorhus/electron-store/assets/50284575/14aeda51-6221-41d2-974e-a88508ec115c)

**Comment by sindresorhus** [comment]
This seems like a problem with your bundler, not this package.
