### ISSUE TITLE
Error [ERR_REQUIRE_ESM]: require() of ES Module

### ISSUE THREAD

**Issue by codeparl** [sindresorhus/electron-store#287]
In my electron app I started the app in dev mode but got an error indicating that change the require of [\node_modules\electron-store\index.js] to import

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

**Comment by ryanhugh** [comment]
CJS support would be great, ESM is painful to use.
