### ISSUE TITLE
How to append a list/array?

### ISSUE THREAD

**Issue by pujiaxun** [sindresorhus/electron-store#32]
What I've known is to _get_ and _append_ and _set_ .
```js
list = store.get('list')
list.push(foo)
store.set('list', list)
```

Is this the only way?

Any shortcuts like `store.push('list', foo)`

Thanks~

**Comment by kmb266** [comment]
Try something like this
`
  var list = store.get('list');
  if (list) {
    store.set('list', list.push(foo));
  }
  else {
    store.set('list', [foo]);
  }
`

**Comment by Slapbox** [comment]
@kmb266 great answer. You need to use `.concat` though instead of `.push`

**Comment by sindresorhus** [comment]
I'm open to adding a convenience method to push to an array and create one first if it doesn't exist. Sounds like a common need. It should throw if there's a value already and it's not an array. Could be named `.arrayPush()`, but open to suggestions for a better name.

**Comment by Slapbox** [comment]
@sindresorhus I went another route, but I agree this would be a useful feature.

**Comment by sindresorhus** [comment]
Closing this in favor of #52
