### ISSUE TITLE
App Data Persists after App Delete

### ISSUE THREAD

**Issue by chukkwagon** [sindresorhus/electron-store#33]
The default location for stores (`~/.config/AppName` on linux) is not deleted when the app is uninstalled. Is this intentional? Do you have a recommendation for how to delete the data when the app is deleted?

**Comment by sindresorhus** [comment]
I'm not a Linux user, but I think that depends on how you installed the app (deb, rpm, AppImage, etc). `electron-store` doesn't have any knowledge of how your app is installed nor should it.

**Comment by chukkwagon** [comment]
@sindresorhus that's correct, and I actually found some configuration options in the build package I am using that allow me to delete app data on uninstall. Thanks

**Comment by kousiksatish** [comment]
@chukkwagon I am facing the same issue. Can you let me know if you are using electron-builder for packaging and which configuration option you changed to get this done?

**Comment by dtboy1995** [comment]
> @chukkwagon I am facing the same issue. Can you let me know if you are using electron-builder for packaging and which configuration option you changed to get this done?

"nsis": {
  "deleteAppDataOnUninstall"}

**Comment by Thesiva7** [comment]
@chukkwagon Hi, i am facing same issue in linux. don't know to how to delete the electron store data from **~/.config/AppName** on uninstalling the electron app in linux. for window we have **deleteAppDataOnUninstall**. for linux we have **afterRemove**. but after remove script is not taking $HOME or ~/.config/AppName to delete app data.

can you please help me on this.
Thank you.
