### ISSUE TITLE
Invalid JSON file corrupts store data

### ISSUE THREAD

**Issue by bampakoa** [sindresorhus/electron-store#35]
When the file that is passed to the store options is not a valid JSON, the contents of the file are overwritten to an empty object. Is there any built-in way to overcome this or should I check the validity of the file before calling the ctor of the store?

**Comment by sindresorhus** [comment]
That's intentional. You're not supposed to use an existing file. Why are you doing that?

**Comment by bampakoa** [comment]
I use the library for storing application settings. Before I call `store.get()` method to read a setting, I initialize the store as `let store = new Store(options)`.

**Comment by sindresorhus** [comment]
What would you expect to happen? I would argue it's better to just wipe the store than for the app to throw an error and not work.

**Comment by bampakoa** [comment]
That's very true in case the application manipulates the store by itself. On the other hand, which is my case, where the application can also be started externally from another program which is responsible to supply the configuration file, I think it is not appropriate to alter the external file even if it is wrong

**Comment by sindresorhus** [comment]
I'd be happy to merge a PR with an option to throw instead of clearing out the store on invalid JSON, but the default should be clearing out.

**Comment by bampakoa** [comment]
That would be great! I would be happy to help.
