### ISSUE TITLE
Support for overriding file extension

### ISSUE THREAD

**Issue by trodi** [sindresorhus/electron-store#36]
This may be out of scope for the intended purpose of the module. Currently you can't override the extension used, just the name and location. With the move to a more generic name (#4) to represent a larger use case for this module, does it make sense to allow overriding the extension?

For example, I could use `electron-store` to interact with a file with a custom file extension that can be associated with my electron app. These might be simple save/export/preference files that are intended to be shareable or saved outside of the application. It may still be a `json` file or an "encrypted" `json` file, but the user need not know that.

1. Is this use case something the module is okay supporting?
2. If so, are you open to a PR?

**Comment by sindresorhus** [comment]
PR welcome :)

Should be implemented in https://github.com/sindresorhus/conf and also documented here. The docs should include the use-cases mentioned above. The option name should be `fileExtension`.
