### ISSUE TITLE
The `onDidChange` event is not propagating to all windows

### ISSUE THREAD

**Issue by zeke** [sindresorhus/electron-store#39]
I've got two windows open. One of them changes the state object.

```js
store.set('preferences', newPrefs)

document.addEventListener('DOMContentLoaded', () => {
  store.onDidChange('preferences', (newValue, oldValue) => {
    console.log('hello from setting window', newValue, oldValue)
    // works!
  })
})
```

Another open window is also subscribed to the event, but it doesn't fire:

```js
document.addEventListener('DOMContentLoaded', () => {
  store.onDidChange('preferences', (newValue, oldValue) => {
    console.log('hello from receiving window', newValue, oldValue)
    // does not work :[
  })
})
```

**Comment by zeke** [comment]
Perhaps I should only manipulate `store` from the app's main process, and use IPC to collect and distribute updates to and from all the windows? 🤔

**Comment by sindresorhus** [comment]
Yes, the events only work in the same process as they were triggered. To make this work we would have to propagate events between the windows and the main process. It's definitely doable, but not trivial.

**Comment by deadcoder0904** [comment]
Can this be done like you did https://github.com/sindresorhus/electron-better-ipc ❓

So `onDidChange` will be in both `main` & `renderer`❓But it seems like `electron-store` uses `conf` so you would need another module named `electron-conf` where `onDidChange` can be put in both `main` & `renderer` right❓I'm just guessing :)

**Comment by JamesCoyle** [comment]
Couldn't this be achieved with `fs.watch` on the file that can trigger events wherever store is used?

**Comment by sindresorhus** [comment]
We now have a [`watch`](https://github.com/sindresorhus/electron-store#watch) option.

**Comment by zeke** [comment]
Nice! That works for my use case. Feel free to close this.

**Comment by duyleekun** [comment]
@sindresorhus  I think we should close this issue and remove the note in https://github.com/sindresorhus/electron-store/blob/master/readme.md#ondidchangekey-callback
