### ISSUE TITLE
More general name needed

### ISSUE THREAD

**Issue by leo** [sindresorhus/electron-store#4]
IMHO, this package can be used for either the config or just for saving/caching data (like we're doing it in [Now Desktop](https://github.com/zeit/now-desktop)). Because of this, I recommend renaming it.

My suggestion is "electron-store" (the package name is available on npm).

**Comment by danielnieto** [comment]
that's what I think too... I do not want to store config, but some cached data

**Comment by tiemevanveen** [comment]
It works great as a persistent store! 

But is that the way it's meant to be used? Doesn't it write your changes to disk everytime you **set** something, and won't it read the file back in every time you **get** something? That is not very efficient for a store right? Or shouldn't we worry too much about that? Something with [premature-optimization](http://softwareengineering.stackexchange.com/questions/80084/is-premature-optimization-really-the-root-of-all-evil) being evil 😈  ?

Upside is of course that it gives you persistence even when your app is abruptly terminated 😄

**Comment by sindresorhus** [comment]
@leo Done at last. Thanks for the idea.

@teameh It shouldn't be a problem for most use-cases. Fs isn't that slow. And synchronous fs is faster than async, because async has overhead with event-loop. This is indeed a premature-optimization. If you encounter the need to use it in a hot code path, you could always set everything at once with `.set(object)`.

**Comment by leo** [comment]
Wonderful new name! ❤️

**Comment by prajapati-parth** [comment]
Would this have any impacts on projects that used `electron-config`. Should any migration steps be followed? Because npm still has a package named `electon-config`.

Thanks.
