### ISSUE TITLE
Append item to Stored json array (QUESTION)

### ISSUE THREAD

**Issue by harveylewis** [sindresorhus/electron-store#44]
Is there a way I can append an item to a list that is stored? For example:

`store.set("listOfItems", [{
"name" : "John"}])`

how would I then add another item to `store.get("listOfItems")` 
thanks for any help from anyone

**Comment by bentorkington** [comment]
Since this question ranks highly in Google results, see [here](https://github.com/sindresorhus/electron-store/issues/32)
