### ISSUE TITLE
Failed to minify the code.

### ISSUE THREAD

**Issue by joshuapinter** [sindresorhus/electron-store#45]
Hey There, 

Using this in our Electron app, which is a React app. 

When I run `npm run build` I get the following error message:

```
Failed to minify the code from this file: 

 	./node_modules/electron-store/index.js:6 

Read more here: http://bit.ly/2tRViJ9
```

If you follow [the link](http://bit.ly/2tRViJ9) it says to:

> Open an issue on the dependency's issue tracker and ask that the package be published pre-compiled.

Let me know your thoughts on this. 

Thanks!

**Comment by sindresorhus** [comment]
This module uses modern JS syntax as it targets Electron, not browsers. The fact that Create React App doesn't support that is not a concern of this module. CRA 2 will fix this.

**Comment by joshuapinter** [comment]
For others running into this that are running Electron 1.x apps, you can use **[`electron-storage`](https://github.com/Cocycles/electron-storage)** until you upgrade. The interface isn't quite as nice but it compiles just fine.
