### ISSUE TITLE
Windows line ends

### ISSUE THREAD

**Issue by alexbfree** [sindresorhus/electron-store#47]
Hi, I was just wondering if there is a way to set electron store to use the full CR+LF windows line ends, so that my application users can open the files in Notepad? (currently it uses unix line ends so the file doesn't display properly unless they use an IDE/Notepad++ etc). Thanks if you can help!

**Comment by sindresorhus** [comment]
No, and not interested in supporting that.

Relevant: https://www.theverge.com/2018/7/12/17563704/microsoft-windows-notepad-app-update

**Comment by alexbfree** [comment]
OK thanks
