### ISSUE TITLE
Multiple instance store

### ISSUE THREAD

**Issue by xgdgsc** [sindresorhus/electron-store#48]
It seems if I want to run multiple instances of one app with different data configs. It would write into the same config.json file. Is there a recommended way of using it with multiple instances, or using something else?

**Comment by sindresorhus** [comment]
You can specify the `name` option with a different value than `config`.

**Comment by Slapbox** [comment]
@sindresorhus is it possible to store across multiple (sub)folders?

Can you explain the rationale behind this warning on setting `cwd`:

> _Don't specify this unless absolutely necessary!_
