### ISSUE TITLE
Usage with TypeScript?

### ISSUE THREAD

**Issue by gremo** [sindresorhus/electron-store#49]
Is not clean how to use with Typescript. Here is the typings definition: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/electron-store any help is much apprecciated!

**Comment by sindresorhus** [comment]
The type definitions are not made by me and are unofficial. Any support for them should be directed to the https://github.com/DefinitelyTyped/DefinitelyTyped project.

**Comment by sindresorhus** [comment]
That being said, there's a clear example right there: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/5e58f71c5e96c7c4bfc316f3b5b3f39124027609/types/electron-store/electron-store-tests.ts#L1
