### ISSUE TITLE
Increased bundle size with JSON schema support

### ISSUE THREAD

**Issue by bampakoa** [sindresorhus/electron-store#60]
After trying version 3.1.0 of the library, I noticed that **ajv** library is included in `node_modules` as a dependency which increases the overall size of an electron bundle by **1.5 MB**. Is this something that could be made optional for use cases that do not need JSON schema validation?

**Comment by sindresorhus** [comment]
1.5 MB is no fun, but it's also negligible compared to the total size of an Electron app. I don't think it's worth forcing people to manually depend on `ajv` if they want it. Schema support is one of the big selling points of `electron-store` now. It lets you be a lot more confident about using it. The `ajv` package directory is also just 240 KB compressed.

I think it would be better to help `ajv` reduce their package size, which would benefit a lot more users: https://github.com/epoberezkin/ajv/issues/940

Alternatively, you could use Yarns dependency override feature to replace `ajv` with a noop package. Or use https://yarnpkg.com/lang/en/docs/cli/autoclean/ or https://github.com/ModClean/modclean to clean up unneeded files (this might get you even more size reduction than removing `ajv`).

**Comment by bampakoa** [comment]
@sindresorhus could you please clarify a bit? Even if use one of the two clean packages, the statement `const Ajv = require('ajv');` will still be there. Isn't it?

**Comment by sindresorhus** [comment]
Yes

**Comment by bampakoa** [comment]
Thanks! I would like also to add that you need to mock the `ajv` package additionally to what you have mentioned about removing it from `node_modules`
