### ISSUE TITLE
Cannot read property 'app' of undefined when using child_process.fork

### ISSUE THREAD

**Issue by alirezavalizade** [sindresorhus/electron-store#63]
Thanks for this cool package, I'm trying to write bunch of shits for several time on my store, but it's little bit slow, so i decided to use `child_process.fork` to try it,
but I'm getting an error,

```
/node_modules/electron-store/index.js:8
const defaultCwd = (electron.app || electron.remote.app).getPath('userData');
```

**Comment by alirezavalizade** [comment]
I tried and hard coded the `defaultCwd ` variable and it worked correctly, Anyway but it's still slow, 
do you have any idea how to `increase` the performance? @sindresorhus

**Comment by sindresorhus** [comment]
`.fork()` by default spawns Electron in Node.js mode: https://github.com/electron/electron/issues/6656
