### ISSUE TITLE
TypeScript error when setting the store

### ISSUE THREAD

**Issue by schnetzi** [sindresorhus/electron-store#64]
I am using electron with vue. After updating to electron 5 (from 4.0.7) and electron-store 3.2 (from 2.0) I get errors in my settings file: `Type 'ServerConfig' has no properties in common with type 'ISettings'.ts`

I am initializing the store with the following:
```js
storage = new Store<ISettings>({})
```
where `ISettings` is an interface for settings and looks like this:
```js
export interface ISettings {
	serverConfig?: ServerConfig;
	language?: string;
}
```

The error shows up when I want to add the serverConfig for example to the store. I am doing this the following way:
```js
this.storage!.set('serverConfig', serverConfig);
```

Am I doing something wrong there or is there somewhere a bug?

**Comment by sindresorhus** [comment]
// @BendingBender

**Comment by KillerCodeMonkey** [comment]
@sindresorhus @schnetzi 
i thought this is a problem, too.
But if you check out the `config` repo and the typings you would see that you need to type your schema in a different way:

1. the generic of the contructor is only for typing the *values* (not keys) of your schema
like

```TS
const store = new Store<number | string>({
  defaults: {
    whatever: 1 // only numbers and strings are allowed
  }
})
```
2. if you want to validate against a schema you have to use the schema key and define your schema with https://github.com/epoberezkin/ajv/blob/master/KEYWORDS.md#keywords-for-arrays

**Comment by brunolemos** [comment]
I made the same upgrade and I’m getting some errors that wasn’t happening as well. It’s not correctly getting the type of each config individually like it was before:

![image](https://user-images.githubusercontent.com/619186/60546674-2ba99c80-9cf4-11e9-8b30-fde5625503d0.png)

**Comment by sindresorhus** [comment]
The TS types were previously not very good. They are much improved in the latest version. You can now properly have a strongly-typed store. [Example](https://github.com/sindresorhus/electron-store/blob/17a8b7ab27606c9a52689a4ef6ae39893a4156d4/index.test-d.ts#L38-L59).

https://github.com/sindresorhus/electron-store/releases/tag/v5.0.0

However, the types could still be improved: https://github.com/sindresorhus/conf/issues/86 For example, there's no way to use a dot-path like `store.get('foo.bar')` with a typed store.
