### ISSUE TITLE
Unsubscribe from onDidChange listener - React

### ISSUE THREAD

**Issue by gomorizsolt** [sindresorhus/electron-store#65]
What's the proper way of unsubscribing from the `onDidChange` event?

---

**Details**

My concern is that I couldn't find any relevant part in the doc that'd explain how to unsubscribe from the `onDidChange` event.

Let's suppose that we listen to `data` changes and each change results in a `this.setState` call:
```js
componentDidMount() {
   store.onDidChange("data", newData => {
      this.setState({
         data: newData
      });
   });
}
```

However, whenever the component is unmounted and the `onDidChange` event is fired,  it throws the - expected - error in the console:

> Can't perform a React state update on an unmounted component. This is a no-op, but it indicates a memory leak in your application. To fix, cancel all subscriptions and asynchronous tasks in the componentWillUnmount method.

One solution might be to "modify" the `onDidChange` event whenever the component is being unmounted, e.g.:

```js
componentWillUnmount() {
   store.onDidChange("data", () => null);
}
```

But this'd cause a memory leak error:

> MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit

I couldn't figure out how to tackle the issue. Could anyone either give a clear explanation or propose a solution? That'd be appreciated.

**Edit**

AFAIU, the `change` event [**removing**](https://github.com/sindresorhus/conf/blob/master/index.js#L201) is handled by the package, thus it's a React specific issue, right?

**Comment by gomorizsolt** [comment]
After further investigations, figured out an acceptable solution:

```js
class Something extends Component {
   constructor(props) {
      super(props);
      
      this.state = { ... };

      // onStateChange is a function that updates the state.
      this.removeListener = globalStore.onDidChange("messages", this.onStateChange);
   }

   componentWillUnmount() {
      // Because handleChange returns  a function that removes the listener.
      this.removeListener();
   }
}
```

**Comment by incizzle** [comment]
How would this be done in react hooks?
