### ISSUE TITLE
Bad File descriptor, close

### ISSUE THREAD

**Issue by Crazie-ash** [sindresorhus/electron-store#66]
![IMG-20190511-WA0017](https://user-images.githubusercontent.com/45698249/57626779-44c78400-75b4-11e9-96fb-cc511b6966c0.jpg)

My application throws some error.. but runs fine... i m not sure why electron store behaving so... Pls have look at the reference screenshot attached..

**Comment by sindresorhus** [comment]
While the error might come from `electron-store`, this is a problem with Electron or Node.js.
