### ISSUE TITLE
Replace 'unknown' types in TypeScript definitions with 'any'

### ISSUE THREAD

**Issue by ramtinsoltani** [sindresorhus/electron-store#68]
Unknown in TypeScript is usually used for casting to other types if they're not convertible to one another (to tell the compiler "I know what I'm doing!"). Using it in the type definitions forces type casts when using the API.

Example:
```ts
public getWrapper(key: string): string {
  return this.storage.get(key);
}
```

> Type 'unknown' is not assignable to type 'string'.

Enforces the following type cast:
```ts
public getWrapper(key: string): string {
  return <string>this.storage.get(key);
}
```

The norm in TypeScript is to use the type `any` whenever we're unsure of a data type. Therefore, the method `.get` should not return `unknown` but it should return `any`. Same goes with the arguments (`defaultValue`, `value`, etc.)

**Comment by sindresorhus** [comment]
> Using it in the type definitions forces type casts when using the API.

Yes, that's exactly the intention. `unknown` is the new better `any`. Using `any` would make the types totally pointless as it could implicitly be converted to anything.

> The norm in TypeScript is to use the type any whenever we're unsure of a data type.

That's the legacy norm. TypeScript is getting stricter and that's a good thing.

> Same goes with the arguments (defaultValue, value, etc.)

`unknown` is a top-type, just like `any`, so they are mostly interchangeable as argument types, so I prefer using `unknown` for consistency.
