### ISSUE TITLE
index.d.ts missing

### ISSUE THREAD

**Issue by flaushi** [sindresorhus/electron-store#71]
I am just migrating from JS to TS.

The file "index.d.ts" is mentioned in package.json, but after `npm i electron-store` it is missing in `node_modules/electron-store`. I think this is the reason for VS Code to complain 
![Bildschirmfoto 2019-06-17 um 12 28 42](https://user-images.githubusercontent.com/15819451/59598008-7e336800-90fb-11e9-9209-25f12c5bb96e.png)

**Comment by sindresorhus** [comment]
The types are there. Make sure you're on the latest version. The types were added in v3.2.0. You might also need to import is using `import store = require('electron-store');` as it's a CommonJS module.

**Comment by flaushi** [comment]
Jep, sorry, had to restart VSC. Also thanks for your hint about the importing.
