### ISSUE TITLE
Should the minimum version of node be required?

### ISSUE THREAD

**Issue by zce** [sindresorhus/electron-store#73]
The `worker_threads` module can only be used directly in Node v11+, This does not affect the use of it in Electron 5. But if I use webpack to package the main thread code, I need Node v11+

![v10](https://user-images.githubusercontent.com/6166576/60076725-dd782480-975a-11e9-8541-84157184b31f.png)

![v11](https://user-images.githubusercontent.com/6166576/60076426-1b287d80-975a-11e9-8d25-4911a5773a0a.png)

![v12](https://user-images.githubusercontent.com/6166576/60076452-31ced480-975a-11e9-97c5-d3dda0b0bbb7.png)

Maybe you should add the `engines` field to the `package.json` file or note it in the document

**Comment by sindresorhus** [comment]
No, this is completely unrelated to the actual package. This is a Webpack issue.

https://github.com/npm/write-file-atomic/issues/41

**Comment by zce** [comment]
Thanks
