### ISSUE TITLE
Store is not a constructor

### ISSUE THREAD

**Issue by mscoobby** [sindresorhus/electron-store#74]
Hello, I've stumbled across a problem.
I'm trying to import the library with `import * as Store from 'electron-store` since using `import Store = require('electron-store')` gives an error `Import assignment cannot be used when targeting ECMAScript modules.`
But importing it like that gives another error `Store is not a constructor` any ideas how to solve the problem? I don't want to use `const Store = require('electron-store')` because my tslint complains about it.

**Comment by sindresorhus** [comment]
The correct way to import is: `import store = require('electron-store');`

We even have a test to prove it's working: https://github.com/sindresorhus/electron-store/blob/e205086864340db1525ccdccaa2ee9b741bced3f/index.test-d.ts#L2

**Comment by mscoobby** [comment]
I know it's working this way but the linter complains so actually it's not the "correct" way.

**Comment by gungorbudak** [comment]
@mscoobby How did you solve this? I get following with the correct way.

```
'import ... =' can only be used in TypeScript files.ts(8002)
```

**Comment by mscoobby** [comment]
@gungorbudak I ended up declaring the `ElectronStore` type
```
type ElectronStore = {
  get: (key: string) => any
  set: (key: string, value: any) => void
}
```
And still using `const Store = require('electron-storel)` I was not able to make it work properly with `import`

**Comment by SairajK19** [comment]
@mscoobby just use `const store = require(' .');`
It works without the curly braces.
