### ISSUE TITLE
Snap compatibility — SNAP_USER_DATA must be used if defined.

### ISSUE THREAD

**Issue by develar** [sindresorhus/electron-store#75]
Please see https://github.com/anujdatar/onenote-desktop/issues/7

Access to home is forbidden if electron app is packed as snap. `SNAP_USER_DATA` must be used if defined.

**Comment by sindresorhus** [comment]
This should really be opened on Electron as I’m just using the userData directory provided by Electron.

**Comment by develar** [comment]
Thanks for quick reply, you are right, it should be fixed in electron-builder. https://github.com/electron-userland/electron-builder/issues/4038

**Comment by anujdatar** [comment]
thanks for the quick replies guys.

**Comment by develar** [comment]
Still cannot make it working, because of https://github.com/npm/write-file-atomic/blob/8f0f33e82577749a47e778a8234773163a3ed2fe/index.js#L196
<img width="514" alt="Screenshot 2019-07-10 at 21 53 59" src="https://user-images.githubusercontent.com/350686/61000204-3e0f8000-a35d-11e9-84b7-54016a1b9f8a.png">

**Comment by develar** [comment]
Still doesn't work because of strange chown https://github.com/npm/write-file-atomic/blob/8f0f33e82577749a47e778a8234773163a3ed2fe/index.js#L196

<img width="658" alt="Screenshot 2019-07-10 at 22 27 13" src="https://user-images.githubusercontent.com/350686/61002496-efb0b000-a361-11e9-8221-0e7f1faddff8.png">

**Comment by sindresorhus** [comment]
@develar See: https://github.com/npm/write-file-atomic/issues/49
