### ISSUE TITLE
Recover default value

### ISSUE THREAD

**Issue by MrAmericanMike** [sindresorhus/electron-store#80]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2440%20Funded-%2300A156.svg" />](https://issuehunt.io/r/sindresorhus/electron-store/issues/80)

I know the "get" method has an argument that is the default value to return in case the item doesn't exists.

Is there a way to get that value, even if the item exists? Or I would have to delete the key and call get on it?

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $40.00)

- [<img src='https://avatars3.githubusercontent.com/u/44827199?v=4' alt='issuehunt' width=24 height=24> issuehunt](https://issuehunt.io/u/issuehunt) ($40.00)
### Submitted pull Requests
- [#84 Added [reset] method](https://issuehunt.io/r/sindresorhus/electron-store/pull/84)
---

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/sindresorhus/electron-store/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by sindresorhus** [comment]
What is your use-case? It would be helpful to know what specifically you need it for.

**Comment by MrAmericanMike** [comment]
For example a value that a user is changing on some configs from default 40 to let's say 77 and I want to have a button so the user can "Reset to default" and make that field 40 again.

**Comment by sindresorhus** [comment]
I agree. I think it could be useful with a `store.reset(key)` method.

**Comment by MrAmericanMike** [comment]
Thanks. Glad you liked the idea ;)

**Comment by ShadyThGod** [comment]
Any updates on when this is going to get implemented?

**Comment by MrAmericanMike** [comment]
> 
> 
> Any updates on when this is going to get implemented?

I believe this is already implemented

https://github.com/sindresorhus/electron-store/pull/84

I will be doing some tests tomorrow, but I believe it's all done ;)

**Comment by MrAmericanMike** [comment]
Ok so I have run a simple test, and I don't think it's working.

`const Store = require('electron-store');
const store = new Store();

store.delete('test');

let value = store.get('test', 'Hola');

console.log(value);

store.set('test', 'Manola');

value = store.get('test');
console.log(value);

store.reset('test');

value = store.get('test');
console.log(value);

`
The console out is 

> Hola
Manola
Manola

I wonder what I'm missing here.
