### ISSUE TITLE
replace spread operator

### ISSUE THREAD

**Issue by mgrundkoetter** [sindresorhus/electron-store#87]
As you can see in your forks (https://github.com/MarkForged/electron-store/commit/6500a6475680161abb4757cb3956de4864f33200) the spread operator is not a good idea there (yet). At first, the whole thing is not backward compatible, on the other hand it is crashing even in newer versions when webpack is used.
For instance when using frameworks like vue or react inside electron, using your electron-store will already crash with the line `const Store = require('electron-store');` as the spread operator will not be recognized correctly (Unexpected token ...)
See https://github.com/electron-userland/electron-webpack/issues/65

**Comment by sindresorhus** [comment]
Both Babel and Webpack support object spread and have for a long time. The fact that electron-webpack uses an outdated plugin/preset is not really something this package should concern itself with. I use syntax that works in the Electron version I target. If you use outdated tools, then it's up to you to work around it, sorry.

**Comment by mgrundkoetter** [comment]
Ok, maybe the provided links are a little confusing. I use the most recent versions of electron (6.0.11), react (16.9.0) and everything else, so nothing outdated at all. Also, it's not about the spread operator in general, but just the way it is used here (merging options). If you set up a new electron app with react or vue (everything most recent versions ;-), your module will crash as described just be requiring it. If you do not desire to be compatible to this combination of tools, everything is fine. I indeed found a workaround for it: just use another module (electron-settings) instead of this one.
