### ISSUE TITLE
using jest: ElectronStore is not a constructor

### ISSUE THREAD

**Issue by flaushi** [sindresorhus/electron-store#89]
Hey, I am no pro with nodejs, I'd be grateful for some help.

I am trying to mock `electron` in my jest test suite, because the ElectronStore constructor calls 
```
const defaultCwd = (electron.app || electron.remote.app).getPath('userData');
```
So I have a `jest.config.js`:
```
module.exports = {
    "roots": [
      "<rootDir>/src"
    ],
    "transform": {
        "^.+\\.tsx?$": "ts-jest"
    },
    "testPathIgnorePatterns" : ['mocks'],
    "moduleNameMapper": {
        "electron" : "<rootDir>/mocks/electronMock.js"
    }
  }
```
and the `electronMock.js`
```
module.exports = {
    app: {
        getPath: jest.fn().mockReturnValue('.')
    }
}
``` 
But I get the following error message:
```
TypeError: ElectronStore is not a constructor

       5 | import * as XLSX from 'xlsx';
       6 | import  ElectronStore = require('electron-store');
    >  7 | const store = new ElectronStore();
         |               ^
```

THANKS A LOT IN ADVANCE!!!

**Comment by sindresorhus** [comment]
This is not related to `electron-store`.

Googling it gives some maybe helpful results:
- https://github.com/facebook/jest/issues/5023
- https://www.google.com/search?q=jest+mock+TypeError%3A+is+not+a+constructor&oq=jest+mock+TypeError%3A++is+not+a+constructor&aqs=chrome..69i57.3333j0j1&sourceid=chrome&ie=UTF-8
