### ISSUE TITLE
onDidChange only fires once (reactjs)

### ISSUE THREAD

**Issue by iluxdev** [sindresorhus/electron-store#93]
```js
const Store = window.require("electron-store")
const store = new Store({ watch: true })

function App() {

store.onDidChange("key", (newValue, oldValue) => {
    console.log("DID CHANGE", newValue)
})

 return (
            <App />
    )
}
```
when store.set("key", value) is called for the first time, the onDidChange callback fires, but after that, nothing.

**Comment by oscadev** [comment]
Try putting the code inside a useEffect rather than just inside the function.

**Comment by docoder** [comment]
same problem
@oscadev that not work

**Comment by maximeallanic** [comment]
It's a `conf` module issue:
https://github.com/sindresorhus/conf/issues/108

**Comment by ali-farooq0** [comment]
Is there a workaround to this issue?

**Comment by balancelove** [comment]
Is there a solution to this problem?

**Comment by sindresorhus** [comment]
A fix was published in `conf`. Just reinstall the latest version of `electron-store` to get the fix.
