### ISSUE TITLE
How to use encryptionKey? [Question]

### ISSUE THREAD

**Issue by Nabeel20** [sindresorhus/electron-store#94]
I didn't understand the document , any help or examples? 
Thanks

**Comment by lukesUbuntu** [comment]
```
const yourEncryptionKey = 'MyStrongEncryptionKey';
const store = new Store({ encryptionKey: yourEncryptionKey });
```

**Comment by mahadevans87** [comment]
@lukesUbuntu Can't someone view the source and get this encryption key? How secure is it?

**Comment by lukesUbuntu** [comment]
@mahadevans87 yes that is correct most apps can be reverse engineered that being said you do have options on making your encryption key a bit more secure, i wrote a [native module in c++](https://www.electronjs.org/docs/glossary#native-modules)  that handles the encrypted key code for my electron apps. 


You can also obfuscate your key code and put it into an [ASAR](https://www.electronjs.org/docs/glossary#asar).  I use [jscrambler](https://jscrambler.com/) to obfuscate code and some projects [UglifyJS](https://github.com/mishoo/UglifyJS) works just fine. It makes it harder to find the key code and encryption key.
