### ISSUE TITLE
Issue when trying to load the electron-store

### ISSUE THREAD

**Issue by VaishakVk** [sindresorhus/electron-store#97]
Hi I am trying to run the simplest of code here. However I am getting the error 
`
const Store = require("electron-store");

const store = new Store();
`

Error: 

> TypeError: Store is not a constructor
 
I am running on Electron App

**Comment by VaishakVk** [comment]
Solved

**Comment by pjebs** [comment]
Was your issue similar to this: https://github.com/sindresorhus/electron-store/issues/98

How did you solve it?
