### ISSUE TITLE
How to use in Main process

### ISSUE THREAD

**Issue by HiZhaoYun** [sindresorhus/electron-store#99]
I create a web app use Electron and CRA, and use electron-store in main.js:

```
const {app, BrowserWindow, ipcMain} = require('electron');
const path = require('path');
const url = require('url');
const Store = require('electron-store');

const SettingsStore = new Store({
    name: "Settings",
});
```

when i use the app that packed by electron-builder, it report a error :
![image](https://user-images.githubusercontent.com/59190880/72678119-d4c3b300-3add-11ea-846e-3ec5e12b90df.png)

**Comment by sindresorhus** [comment]
That is a problem with your build config or CRA. It has nothing to do with this package. This package works fine when used normally without CRA.

I'm using it in production here: https://github.com/sindresorhus/caprine/blob/3b640acc42913d58d1d62d47eb27c4278406bc88/package.json#L34
